[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
print_stdout = "warn"
arithmetic_side_effects = "warn"
as_conversions = "warn"
integer_division = "warn"
