[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
print_stdout = "warn"
arithmetic_side_effects = "warn"
as_conversions = "warn"
integer_division = "warn"
