[package]
name = "knap_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
knap_base = { path = "../knap_base" }
knap_window = { path = "../knap_window" }
ropey = "1.6.1"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.0"

[lints]
workspace = true
